### ISSUE TITLE
pip install failing (need new release?)

### ISSUE THREAD

**Issue by chrishavlin** [yt-project/yt_idv#33]
Just tried a pip install from a fresh environment and found that the version up on pypi doesn't actually install:

```
$ pip install yt-idv
Collecting yt-idv
  Downloading https://files.pythonhosted.org/packages/22/ab/a2734ba6119df221dc811afd960bbd1c185631290f4b968dc996d5159f89/yt_idv-0.2.1.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 1.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yuafjaiq/yt-idv/setup.py", line 12, in <module>
        with open("HISTORY.md") as history_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yuafjaiq/yt-idv/
```

That `HISTORY.md` file exists in the current repo so I suspect this will be fixed whenever we cut a new release?

**Comment by chrishavlin** [comment]
ya, there's a github action, I think it pushes a release if we bump the version number. I'll try!

**Comment by chrishavlin** [comment]
`pip install yt-idv` works again with #36 and the latest release.
